server:
  port: 8083
spring:
  application:
    name: menu
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/coffee
    username: coffee

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        hbm2ddl:
#          import_files: classpath:/data-init.sql
    show-sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:/data-init.sql


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
