services:
  - type: web
    name: coffee-apigw
    env: docker
    runtime: image
    image:
      url: micchecka/coffee-apigw:latest
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  - type: web
    name: coffee-eureka-server
    runtime: image
    image:
      url: micchecka/coffee-eureka-server:latest

  - type: web
    name: coffee-menu
    env: docker
    runtime: image
    image:
      url: micchecka/coffee-menu:latest
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  - type: web
    name: coffee-bucket
    env: docker
    runtime: image
    image:
      url: micchecka/coffee-bucket
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  - type: pserv
    name: postgres
    runtime: image
    image:
      url: micchecka/coffee-db-image
    envVars:
      - key: POSTGRES_USER
        value: coffee
      - key: POSTGRES_PASSWORD
        value: password

  - type: web
    name: pgadmin
    runtime: image
    image:
      url: dpage/pgadmin4
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: pgadmin4@pgadmin.org
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin

  - type: web
    name: zipkin
    runtime: image
    image:
      url: openzipkin/zipkin

  - type: web
    name: redis
    runtime: image
    image:
      url: redis:latest

  - type: web
    name: redis-commander
    runtime: image
    image:
      url: rediscommander/redis-commander:latest
    envVars:
      - key: REDIS_HOSTS
        value: local:redis:6379
