server:
  port: 8080

spring:
  datasource:
    autoconfiguration: false
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG