server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: menu
          uri: lb://MENU
          predicates:
            - Path=/api/v1/menu/**
        - id: bucket
          uri: lb://BUCKET
          predicates:
             - Path=/api/v1/firstAuth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG