version: '1'
services:
  coffee-apigw:
    image: micchecka/coffee-apigw:latest
    ports:
      - "8080:8080"
    networks:
      - default
  coffee-eureka-server:
    image: micchecka/coffee-eureka-server:latest
    ports:
      - "8761:8761"
  coffee-menu:
    image: micchecka/coffee-menu:latest
    ports:
      - "8083:8083"
    networks:
      - postgres
      - default
  coffee-bucket:
    image: micchecka/coffee-bucket
    ports:
      - "8082:8082"
    networks:
      - postgres
      - default

  postgres:
    container_name: postgres
#    image: postgres
    image: micchecka/coffee-db-image
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_coffee
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

networks:
  postgres:
    driver: bridge


volumes:
  postgres:
  pgadmin: