server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: eureka-server

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG