server:
  port: 8082

spring:
  application:
    name: bucket
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/bucket
    username: coffee

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  session:
    store-type: redis
  redis:
    host: redis
    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO